// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntityDataModel.Models
{
    public partial class User
    {
        public User()
        {
            Comments = new HashSet<Comments>();
        }

        public Guid UserId { get; set; }
        public string UserName { get; set; }
        public string ImageUrl { get; set; }

        public virtual ICollection<Comments> Comments { get; set; }
    }
}